### PR TITLE
add mode: :set for sprites

### PR DESCRIPTION
**Pull request by gabrielmancini**
add a sprite generation ability and using by ref

### CODE REVIEW

**Comment by mayel** [comment]
looks great! :)

**Comment by mayel** [comment]
@gabrielmancini Thanks for the contribution! I've added some optimisations (basic caching of the sprite files during dev) and published a release: https://hex.pm/packages/iconify_ex

**Comment by gabrielmancini** [comment]
Hello @mayel ,

 the IO optimization appends the intermediate svgs on file, here https://github.com/bonfire-networks/iconify_ex/blob/3b466a66177dbc41dc770ce53b2c6adf03227cc2/lib/iconify.ex#L186

and because that the family.svg file accumulates instead of override
take a look on svg file
```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <svg id="user-circle"
      xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z">
      </path>
    </svg>

    <svg id="x-mark"
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12"></path>
    </svg>
  </defs>
</svg>
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <svg id="user-circle"
      xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z">
      </path>
    </svg>

    <svg id="arrow-path"
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99"></path>
    </svg>
  </defs>
</svg>

```

the ideal will be something like
```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <svg id="user-circle"
      xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z">
      </path>
    </svg>

    <svg id="x-mark"
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12"></path>
    </svg>

    <svg id="arrow-path"
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99"></path>
    </svg>
  </defs>
</svg>

```

i am try to understand how to fix.

**Comment by mayel** [comment]
That's strange. It seems that's because of including both :read and :write when opening the file, but I can't seem to get a clear answer from reading the docs. Anyway, the optimisation is more about reads, so we can switch back to `File.write` for overwriting.

**Comment by mayel** [comment]
I've pushed that change (plus refreshing the cache when writing, which was probably the actual problem). This library is becoming less simple over time and it's probably time to start adding tests... Anyway, if you could check if that works for you and then I'll release it 🙏

**Comment by gabrielmancini** [comment]
@mayel works like a charm!! 

thanks!

if u had ideas to refactoring the lib, let me know ;-)

**Comment by mayel** [comment]
@gabrielmancini 0.4.1 published

**Pull request merged**
